name: 📦 MLOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v3

    - name: 🐍 Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: 📦 Install dependencies
      run: |
        pip install -r requirements.txt || echo "No requirements.txt found"
        pip install black flake8 pytest

    - name: 🎨 Lint Python code
      run: |
        flake8 scripts/ inference/ lambda/ --ignore=E501
        black --check scripts/ inference/ lambda/

    - name: 🧪 Run unit tests
      run: |
        pytest tests/ || echo "No tests directory yet"

    - name: 🧱 Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: 🔍 Terraform Format Check
      run: terraform fmt -check -recursive

    - name: ✅ Terraform Validate
      run: |
        cd terraform
        terraform init -backend=false
        terraform validate
