name: 🛡️ CodeQL Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * 1'  # Weekly scan (Monday @ 3am UTC)

jobs:
  analyze:
    name: Analyze Python Code
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [python]

    steps:
      - name: 🧾 Checkout Repository
        uses: actions/checkout@v3

      - name: 🧪 Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: 🧪 Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
